parameters:
- name: msbuildPlatform
  displayName: msbuildPlatform
  type: string
  default: x64
  
steps:
- task: CredScan@3
  displayName: 'Run CredScan'
  inputs:
    debugMode: false
  continueOnError: true

- task: BinSkim@4
  displayName: 'Run BinSkim'
  inputs:
    AnalyzeTargetGlob: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\**\*.dll'
  continueOnError: true

- task: DeleteFiles@1
  displayName: 'Delete files from $(Build.BinariesDirectory)\RelWithDebInfo'
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo'
    Contents: |
     **/*.obj
     **/*.pdb
     **/*.dll
      
#Manually set msBuildCommandline so that we can also set CAExcludePath
- task: securedevelopmentteam.vss-secure-development-tools.build-task-prefast.SDLNativeRules@2
  displayName: 'Run the PREfast SDL Native Rules for MSBuild'
  inputs:
    userProvideBuildInfo: msBuildInfo
    msBuildVersion: 16.0
    msBuildArchitecture: x64
    msBuildCommandline: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "$(Build.BinariesDirectory)\RelWithDebInfo\onnxruntime.sln" /p:platform="${{parameters.msbuildPlatform}}" /p:configuration="RelWithDebInfo" /p:CAExcludePath="$(Build.BinariesDirectory);$(Build.SourcesDirectory)\cmake;C:\program files (x86)" /p:VisualStudioVersion="16.0" /m /p:PreferredToolArchitecture=x64'
  continueOnError: true


- task: TSAUpload@2
  displayName: 'TSA upload'
  #condition: and (succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    GdnPublishTsaOnboard: false
    GdnPublishTsaConfigFile: '$(Build.sourcesDirectory)\.gdn\.gdntsa'
  continueOnError: true